In [1]:
import numpy as np

# 1. Creating arrays

** 1.1.  Manual Construction of arrays**

In [3]:
#1-D

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [4]:
#print dimenstions

a.ndim

1

In [5]:
#shape

a.shape

(4,)

In [6]:
len(a)

4

In [7]:
# 2-D, 3-D....

b = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
b.ndim

2

In [9]:
b.shape

(2, 3)

In [10]:
len(b) #returns the size of the first dimention

2

In [11]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [12]:
c.ndim

3

In [13]:
c.shape

(2, 2, 2)

** 1.2  Functions for creating arrays**

In [14]:
#using arrange function

a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b = np.arange(1, 10, 2) #start, end (exclusive), step

b

array([1, 3, 5, 7, 9])

In [16]:
#using linspace

a = np.linspace(0, 1, 6) #start, end, number of points

a

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [19]:
b = np.linspace(0, 1, 5, endpoint=False) #If True, stop is the last sample. Otherwise, it is not included.

b

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

In [20]:
#common arrays

a = np.ones((3, 3))

a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [21]:
b = np.zeros((3, 3))

b

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
c = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

c

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [23]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  0.]])

In [24]:
e = np.eye(3, 3, 1) # rows, columns, index of diagonal start with 1

e

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [25]:
#create array using diag function

a = np.diag([1, 2, 3, 4]) #Extract a diagonal or construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
np.diag(a)   #Extract diagonal

array([1, 2, 3, 4])

In [27]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4) 

a

array([ 0.94122423,  0.47168656,  0.39136305,  0.91688577])

In [28]:
a = np.random.randn(4)   #Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***

a

array([ 0.67909609, -1.06131986, -0.94926945, -0.75779989])

**Note:**
    
For random samples from N(\mu, \sigma^2), use:

sigma * np.random.randn(...) + mu



# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:

In [47]:
a = np.arange(10)

a.dtype

dtype('int64')

In [48]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [50]:
#The default data type is float for zeros and ones function

a = np.zeros((3, 3))

print(a)

a.dtype

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


dtype('float64')

**other datatypes**

In [51]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [52]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


In [56]:
s = np.array(['Ram', 'Robert', 'Rahim'])

s.dtype

dtype('S6')

**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

**For more details**

**https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html**

# 2. Indexing and Slicing

**2.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**:

In [29]:
a = np.arange(10)

print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [30]:
#reverse a sequence is supported in numpy

print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [31]:
# For multidimensional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 3])

print(a[2, 2])

3


In [33]:
a[2, 1] = 5 #assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**2.2 Slicing**

In [34]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [36]:
#perform some slicing operations



In [37]:
#we can also combine assignment and slicing:

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [38]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# 3. Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use **np.may_share_memory()** to check if two arrays share the same memory block. 

**When modifying the view, the original array is modified as well:**

In [39]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [41]:
np.shares_memory(a, b)

True

In [42]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [43]:
a  #now see we modified in b but it updated in a because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [44]:


a = np.arange(10)

c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [45]:
np.shares_memory(a, c)

False

In [46]:
c[0] = 10

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 4. Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Mask**

In [61]:
a = np.random.randint(0, 20, 15)
a

array([ 5, 17, 14,  0,  0,  9, 18,  5,  7,  5, 14,  1, 17,  1, 10])

In [62]:
mask = (a % 2 == 0)

In [63]:
extract_from_a = a[mask]

extract_from_a

array([14,  0,  0, 18, 14, 10])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [64]:
a[mask] = -1
a

array([ 5, 17, -1, -1, -1,  9, -1,  5,  7,  5, -1,  1, 17,  1, -1])

**Indexing with an array of integers**

In [65]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
#Indexing can be done with an array of integers, where the same index is repeated several time:

a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [67]:
# New values can be assigned 

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])